/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as VacaturesRouteImport } from './routes/vacatures'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ExpertisesIndexRouteImport } from './routes/expertises.index'
import { Route as ExpertisesSlugRouteImport } from './routes/expertises.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const VacaturesRoute = VacaturesRouteImport.update({
  id: '/vacatures',
  path: '/vacatures',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesIndexRoute = ExpertisesIndexRouteImport.update({
  id: '/expertises/',
  path: '/expertises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesSlugRoute = ExpertisesSlugRouteImport.update({
  id: '/expertises/$slug',
  path: '/expertises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/vacatures': typeof VacaturesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/expertises/$slug': typeof ExpertisesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/expertises/': typeof ExpertisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/vacatures': typeof VacaturesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/expertises/$slug': typeof ExpertisesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/expertises': typeof ExpertisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/vacatures': typeof VacaturesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/expertises/$slug': typeof ExpertisesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/expertises/': typeof ExpertisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/vacatures'
    | '/blog/$slug'
    | '/expertises/$slug'
    | '/blog/'
    | '/expertises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/vacatures'
    | '/blog/$slug'
    | '/expertises/$slug'
    | '/blog'
    | '/expertises'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/vacatures'
    | '/blog/$slug'
    | '/expertises/$slug'
    | '/blog/'
    | '/expertises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  VacaturesRoute: typeof VacaturesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ExpertisesSlugRoute: typeof ExpertisesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ExpertisesIndexRoute: typeof ExpertisesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacatures': {
      id: '/vacatures'
      path: '/vacatures'
      fullPath: '/vacatures'
      preLoaderRoute: typeof VacaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises/': {
      id: '/expertises/'
      path: '/expertises'
      fullPath: '/expertises/'
      preLoaderRoute: typeof ExpertisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises/$slug': {
      id: '/expertises/$slug'
      path: '/expertises/$slug'
      fullPath: '/expertises/$slug'
      preLoaderRoute: typeof ExpertisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  VacaturesRoute: VacaturesRoute,
  BlogSlugRoute: BlogSlugRoute,
  ExpertisesSlugRoute: ExpertisesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ExpertisesIndexRoute: ExpertisesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
